/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockit;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nizar Maan
 */
public class ClientAccountInfo extends javax.swing.JFrame {

    private static String dummyPwd;

    /**
     * Creates new form ClientAccountInfo
     */
    public ClientAccountInfo() {
        fetchPassword();
        initComponents();
        hideConfirmationLabels();
        setLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangePasswordDialog = new javax.swing.JDialog();
        CurrentPasswordLabel = new javax.swing.JLabel();
        DialogTitle = new javax.swing.JLabel();
        CurrentPasswordField = new javax.swing.JPasswordField();
        NewPasswordField = new javax.swing.JPasswordField();
        ConfirmNewPasswordField = new javax.swing.JPasswordField();
        ConfirmBtn = new javax.swing.JButton();
        ConfirmPwdLabel = new javax.swing.JLabel();
        NewPwdLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ConfirmNewPasswordIncorrect = new javax.swing.JLabel();
        NewPasswordIncorrect = new javax.swing.JLabel();
        CurrentPasswordIncorrect = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        NewPasswordCheck = new javax.swing.JLabel();
        NewPasswordX = new javax.swing.JLabel();
        ClientNameLabel = new javax.swing.JLabel();
        AccountIdLabel = new javax.swing.JLabel();
        SettingsBtn = new javax.swing.JButton();
        AccountId = new javax.swing.JLabel();
        ClientName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AccountTypeLabel = new javax.swing.JLabel();
        CompanyNameLabel = new javax.swing.JLabel();
        AccountType = new javax.swing.JLabel();
        CompanyName = new javax.swing.JLabel();

        ChangePasswordDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ChangePasswordDialog.setTitle(" - Change Password");
        ChangePasswordDialog.setAlwaysOnTop(true);
        ChangePasswordDialog.setResizable(false);
        ChangePasswordDialog.setSize(new java.awt.Dimension(350, 400));
        ChangePasswordDialog.setType(java.awt.Window.Type.POPUP);

        CurrentPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CurrentPasswordLabel.setText("current password");

        DialogTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DialogTitle.setText("Change Password");

        CurrentPasswordField.setToolTipText("your current password");
        CurrentPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CurrentPasswordFieldFocusGained(evt);
            }
        });

        NewPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewPasswordFieldFocusGained(evt);
            }
        });
        NewPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NewPasswordFieldKeyReleased(evt);
            }
        });

        ConfirmNewPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmNewPasswordFieldFocusGained(evt);
            }
        });
        ConfirmNewPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ConfirmNewPasswordFieldKeyReleased(evt);
            }
        });

        ConfirmBtn.setText("Apply Changes");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        ConfirmPwdLabel.setText("confirm new password");

        NewPwdLabel.setText("new password");

        ConfirmNewPasswordIncorrect.setForeground(new java.awt.Color(153, 0, 0));
        ConfirmNewPasswordIncorrect.setText("*");

        NewPasswordIncorrect.setForeground(new java.awt.Color(153, 0, 0));
        NewPasswordIncorrect.setText("*");

        CurrentPasswordIncorrect.setForeground(new java.awt.Color(153, 0, 0));
        CurrentPasswordIncorrect.setLabelFor(CurrentPasswordField);
        CurrentPasswordIncorrect.setText("*");

        NewPasswordCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockit/correct.png"))); // NOI18N

        NewPasswordX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockit/incorrect.png"))); // NOI18N

        jLayeredPane1.setLayer(NewPasswordCheck, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(NewPasswordX, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewPasswordX)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewPasswordX)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ChangePasswordDialogLayout = new javax.swing.GroupLayout(ChangePasswordDialog.getContentPane());
        ChangePasswordDialog.getContentPane().setLayout(ChangePasswordDialogLayout);
        ChangePasswordDialogLayout.setHorizontalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(DialogTitle))
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                                        .addComponent(NewPasswordIncorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewPwdLabel)
                                            .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                                        .addComponent(ConfirmNewPasswordIncorrect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ConfirmPwdLabel)
                                            .addComponent(ConfirmNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ChangePasswordDialogLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(CurrentPasswordIncorrect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CurrentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CurrentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ChangePasswordDialogLayout.setVerticalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(DialogTitle)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CurrentPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentPasswordIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(NewPwdLabel)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewPasswordIncorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addComponent(ConfirmPwdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmNewPasswordIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangePasswordDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(ConfirmBtn)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock It - Account | ");
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ClientNameLabel.setText("Client Name: ");

        AccountIdLabel.setText("Account ID:");

        SettingsBtn.setText("Change Password");
        SettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBtnActionPerformed(evt);
            }
        });

        AccountId.setText("[ID]");

        ClientName.setText("[Name]");

        AccountTypeLabel.setText("Account Type:");

        CompanyNameLabel.setText("Company Name:");

        AccountType.setText("[AccountType]");

        CompanyName.setText("[CompanyName]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CompanyNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CompanyName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AccountTypeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AccountType))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccountIdLabel)
                                    .addComponent(ClientNameLabel))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccountId)
                                    .addComponent(ClientName)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(SettingsBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountIdLabel)
                    .addComponent(AccountId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountTypeLabel)
                    .addComponent(AccountType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyNameLabel)
                    .addComponent(CompanyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SettingsBtn)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBtnActionPerformed
        //create dialog
        resetNewPwdForm();
        ChangePasswordDialog.setVisible(true);
    }//GEN-LAST:event_SettingsBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //can't delete this method, I changed the name of the UI element that it was bound to, so I cant' remove it??
    }//GEN-LAST:event_formWindowClosing

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        // TODO add your handling code here:
        String userPwd = getCurrentPassword();
        String newPwd = getNewPassword();
        String newPwdConfirm = getConfirmedPassword();
        boolean validChange = true;

        if (!userPwd.equals(dummyPwd)) {
            invalidateField(CurrentPasswordField, CurrentPasswordIncorrect);
            validChange = false;
        }
        if (!newPwdConfirm.equals(newPwd) || newPwdConfirm.length() == 0) {
            invalidateField(ConfirmNewPasswordField, ConfirmNewPasswordIncorrect);
            validChange = false;
        }
        if (newPwd.length() == 0) {
            invalidateField(NewPasswordField, NewPasswordIncorrect);
            validChange = false;
        }

        if (validChange) {
            dummyPwd = getNewPassword();
            try {
                DBConnection dbcon = new DBConnection();
                dbcon.establishConnection();
                Statement stmt = dbcon.con.createStatement();
                stmt.executeUpdate("UPDATE account SET password = \""+dummyPwd+"\" where account.Account_ID = "+ClientFrame.getAccountId());
                dbcon.con.close();
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
            resetNewPwdForm();
            ChangePasswordDialog.dispose();
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void ConfirmNewPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfirmNewPasswordFieldKeyReleased
        checkNewPassword();
    }//GEN-LAST:event_ConfirmNewPasswordFieldKeyReleased

    private void NewPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewPasswordFieldKeyReleased
        checkNewPassword();
    }//GEN-LAST:event_NewPasswordFieldKeyReleased

    private void CurrentPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentPasswordFieldFocusGained
        validateField(CurrentPasswordField, CurrentPasswordIncorrect);
    }//GEN-LAST:event_CurrentPasswordFieldFocusGained

    private void NewPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPasswordFieldFocusGained
        validateField(NewPasswordField, NewPasswordIncorrect);
    }//GEN-LAST:event_NewPasswordFieldFocusGained

    private void ConfirmNewPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmNewPasswordFieldFocusGained
        validateField(ConfirmNewPasswordField, ConfirmNewPasswordIncorrect);
    }//GEN-LAST:event_ConfirmNewPasswordFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientAccountInfo().setVisible(true);
            }
        });
    }

    private void checkNewPassword() {
        if (getConfirmedPassword().length() > 0) {
            if (getNewPassword().equals(getConfirmedPassword())) {
                NewPasswordCheck.setVisible(true);
                NewPasswordX.setVisible(false);
            } else {
                NewPasswordCheck.setVisible(false);
                NewPasswordX.setVisible(true);
            }
        }
    }

    private void hideConfirmationLabels() {
        CurrentPasswordIncorrect.setVisible(false);
        NewPasswordCheck.setVisible(false);
        ConfirmNewPasswordIncorrect.setVisible(false);
        NewPasswordIncorrect.setVisible(false);
        NewPasswordX.setVisible(false);
    }

    private void invalidateField(JPasswordField pwdField, JLabel label) {
        label.setVisible(true);
        pwdField.setBackground(new Color(255, 51, 51, 150));
    }

    private void validateField(JPasswordField pwdField, JLabel label) {
        label.setVisible(false);
        pwdField.setBackground(new Color(255, 255, 255, 255));
    }

    private void resetNewPwdForm() {
        validateField(ConfirmNewPasswordField, ConfirmNewPasswordIncorrect);
        validateField(NewPasswordField, NewPasswordIncorrect);
        validateField(CurrentPasswordField, CurrentPasswordIncorrect);
        NewPasswordCheck.setVisible(false);
        NewPasswordX.setVisible(false);
        ConfirmNewPasswordField.setText("");
        NewPasswordField.setText("");
        CurrentPasswordField.setText("");
    }

    private void fetchPassword() {
        try {
            DBConnection dbcon = new DBConnection();
            dbcon.establishConnection();
            Statement stmt = dbcon.con.createStatement();
            String container = ClientFrame.getAccountId();
            ResultSet rs = stmt.executeQuery("select password from account where account.Account_ID = " + ClientFrame.getAccountId());
            while (rs.next()) {
                dummyPwd = rs.getString("password");
                System.out.println(dummyPwd);
            }
            dbcon.con.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    public String getCurrentPassword() {
        return new String(CurrentPasswordField.getPassword());
    }

    public String getNewPassword() {
        return new String(NewPasswordField.getPassword());
    }

    public String getConfirmedPassword() {
        return new String(ConfirmNewPasswordField.getPassword());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountId;
    private javax.swing.JLabel AccountIdLabel;
    private javax.swing.JLabel AccountType;
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JDialog ChangePasswordDialog;
    private javax.swing.JLabel ClientName;
    private javax.swing.JLabel ClientNameLabel;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JPasswordField ConfirmNewPasswordField;
    private javax.swing.JLabel ConfirmNewPasswordIncorrect;
    private javax.swing.JLabel ConfirmPwdLabel;
    private javax.swing.JPasswordField CurrentPasswordField;
    private javax.swing.JLabel CurrentPasswordIncorrect;
    private javax.swing.JLabel CurrentPasswordLabel;
    private javax.swing.JLabel DialogTitle;
    private javax.swing.JLabel NewPasswordCheck;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JLabel NewPasswordIncorrect;
    private javax.swing.JLabel NewPasswordX;
    private javax.swing.JLabel NewPwdLabel;
    private javax.swing.JButton SettingsBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void setLabels() {
        setTitle(getTitle() + ClientFrame.getClientName());
        ClientName.setText(ClientFrame.getClientName());
        AccountId.setText(ClientFrame.getAccountId());
        AccountType.setText(ClientFrame.getAccountType());
        CompanyName.setText(ClientFrame.getCompanyName());
        ChangePasswordDialog.setTitle(ClientFrame.getClientName() + ChangePasswordDialog.getTitle());
    }
}
